version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: remarket_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: remarket
      POSTGRES_PASSWORD: remarket123
      POSTGRES_DB: remarket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U remarket -d remarket"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
